#Bunch of tiling code to clean up - if need for running Omniscape by tile
#Also copy technique used by 03_run_Circuitscape.R
#See 01_Tile_prep.R for cleaner tile code


#If needed.....
#Combining maps
#Stich the map together - clip each tile to the prov_grid tile
ClipTile_function<- function(i) {
  TileClip<-prov_grid %>%
    dplyr::filter(tile_id==i)
  ClippedTile<-CurMapTileList[[i]][[1]] %>%
    crop(vect(TileClip),mask=TRUE)
}

ClippedTileList<-lapply(1:nrow(prov_grid), function (j) {
  ClipTile_function(j)
})

CurrMap<-do.call(terra::merge, ClippedTileList) %>%
  crop(vect(BC),mask=TRUE)
writeRaster(CurrMap, filename=file.path(ConnDir,RunDir,paste0('CurrMap.tif')), overwrite=TRUE)




################

#run as tiles? for larger rasters - still testing
NumTiles<-1
#source("03_analysis_tiles.R")

#split Province into tiles for processing for Omniscape

#Different options are presented
# extent of input layer
ProvBB <- st_bbox(rast(file.path(spatialOutDir,'ProvRast.tif')))

#Number of tile rows, number of columns will be the same
nTileRows <- 2

prov_grid <- st_make_grid(st_as_sfc(bbox_expanded), n = rep(nTileRows, 2))
prov_grid <- st_sf(tile_id = seq_along(prov_grid),
                   geometry = prov_grid, crs = 3005)

# Plot grid and Prov bounding box just to check
plot(prov_grid)
plot(ProvRast,add=TRUE)
writeRaster(ProvRast, filename=file.path(ConnDir,paste0('ProvRast.tif')), overwrite=TRUE)
write_sf(prov_grid, file.path(ConnDir,paste0('prov_grid.gpkg')))
ProvPlt <- st_as_sfc(ProvBB, crs = 3005)
plot(ProvPlt, add = TRUE, col = "green", border = "red")

#Grab a tile
i<-1
AOI.1<-prov_grid %>%
  dplyr::filter(tile_id==i) %>%
  AOI<-st_as_sf(st_as_sfc(tmaptools::bb(st_bbox(AOI.1), ext=1.2)),crs=3005)

#mapview (AOI) + mapview(ProvPlt)+mapview(prov_grid)+mapview(BC)

resistance_surface<-raster(file.path(SpatialDir,paste("resistance_surface.tif",sep="")))
resistance_surface_AOI<-resistance_surface %>%
  mask(AOI) %>%
  crop(AOI) #%>%
#aggregate(fact=pixSize)
#Add a resistance of 1 where ever it is NA
#resistance_surface_AOI[is.na(resistance_surface_AOI)] <- -9999
resistance_surface_AOI[is.na(resistance_surface_AOI)] <- 1

res(resistance_surface_AOI)
saveRDS(resistance_surface_AOI, file = 'tmp/AOI/resistance_surface_AOI')
writeRaster(resistance_surface_AOI, filename=file.path(ConnDir,paste0('resistance_surface_AOI.tif')), overwrite=TRUE)








AOI<-prov_grid
Pcc <- raster::extent(prov_grid[prov_grid$tile_id == i, ])
DefaultRaster <- raster(Pcc, crs = st_crs(BC)$proj4string,
                        resolution = c(100, 100), vals = 0, ext = Pcc)



#Split BC in 2 - get top and bottom extents
BC<-readRDS('tmp/BC')
#20% buffer around BC
BC_bb<-st_bbox(BC)
bufW<-(BC_bb$xmax-BC_bb$xmin)*0.2
BC_20Buff<-BC %>%
  st_buffer(dist=bufW)

#Create top and bottom half
BC_20Buff_e<-ext(BC_20Buff)
new_ymin <- BC_20Buff_e$ymin + (BC_20Buff_e$ymax - BC_20Buff_e$ymin) / 2
# 3. Create new extent objects for bottom and top
bc_half_t<-ext(e$xmin, e$xmax, new_ymin, e$ymax)
bc_half_b<-ext(e$xmin, e$xmax, e$ymin, new_ymin)


mapview(BC)+mapview(BC_20Buff)




# 2. Calculate the ymin halfway point
new_ymin <- e$ymin + (e$ymax - e$ymin) / 2
# 3. Create new extent objects for bottom and top
bc_half_t<-ext(e$xmin, e$xmax, new_ymin, e$ymax)
bc_half_b<-ext(e$xmin, e$xmax, e$ymin, new_ymin)
bc_half<-crop(r,bc_half_b)
# 4. Crop the raster
#r_top_half <- crop(r, top_half_extent)
#extend raster by 1 cell for wall to wall analysis
exX<-round(ncol(bc_half)*0.2,0)
#exY<-round(nrow(bc_half)*0.2,0)
exY=exX
bc_half_ex<-extend(bc_half,c(exX,exY))
AOI<-sf::st_as_sf(as.polygons(bc_half_ex))

resistance_surface<-raster(file.path(SpatialDir,paste("resistance_surface.tif",sep="")))
resistance_surface_AOI<-resistance_surface %>%
  mask(AOI) %>%
  crop(AOI) #%>%
#aggregate(fact=pixSize)
#Add a resistance of 1 where ever it is NA
#resistance_surface_AOI[is.na(resistance_surface_AOI)] <- -9999
resistance_surface_AOI[is.na(resistance_surface_AOI)] <- 1

res(resistance_surface_AOI)
saveRDS(resistance_surface_AOI, file = 'tmp/AOI/resistance_surface_AOI')
writeRaster(resistance_surface_AOI, filename=file.path(ConnDir,paste0('resistance_surface_AOI.tif')), overwrite=TRUE)

#############

break


#If needed.....
#Combining maps
#Stich the map together - clip each tile to the prov_grid tile
ClipTile_function<- function(i) {
  TileClip<-prov_grid %>%
    dplyr::filter(tile_id==i)
  ClippedTile<-CurMapTileList[[i]][[1]] %>%
    crop(vect(TileClip),mask=TRUE)
}

ClippedTileList<-lapply(1:nrow(prov_grid), function (j) {
  ClipTile_function(j)
})

CurrMap<-do.call(terra::merge, ClippedTileList) %>%
  crop(vect(BC),mask=TRUE)
writeRaster(CurrMap, filename=file.path(ConnDir,RunDir,paste0('CurrMap.tif')), overwrite=TRUE)





#Source surface generated by BC_HumanFootprint repo
#extend so can be used for wall to wall

#Resistance surface generated by BC_HumanFootprint repo
resistance_surface<-raster(file.path(SpatialDir,paste("resistance_surface.tif",sep="")))
resistance_surface_AOI.1<-resistance_surface %>%
  mask(AOI) %>%
  crop(AOI) #%>%
#aggregate(fact=pixSize)
#extend raster by 1 cell for wall to wall analysis
exX=round(ncol(resistance_surface_AOI.1)*0.2,0)
#exY=round(nrow(source_surface_AOI.1)/2,0)
exY=exX
#Add a resistance of 1 where ever it is NA
#resistance_surface_AOI[is.na(resistance_surface_AOI)] <- -9999
resistance_surface_AOI[is.na(resistance_surface_AOI)] <- 1

res(resistance_surface_AOI)
saveRDS(resistance_surface_AOI, file = 'tmp/AOI/resistance_surface_AOI')
writeRaster(resistance_surface_AOI, filename=file.path(ConnDir,paste0('resistance_surface_AOI.tif')), overwrite=TRUE)

#writeRaster(resistance_surface_AOI, filename = file.path(ConnDir,paste0('resistance_surface_AOI.ASC')), format = "ascii", overwrite = TRUE)

source_surface<-raster(file.path(SpatialDir,"source_surface.tif"), format="GTiff")
source_surface_AOI.1 <-source_surface %>%
  mask(AOI) %>%
  crop(AOI) #%>%
#aggregate(fact=pixSize)
#extend raster by 1 cell for wall to wall analysis
exX=round(ncol(source_surface_AOI.1)*0.2,0)
#exY=round(nrow(source_surface_AOI.1)/2,0)
exY=exX
source_surface_AOI<-extend(source_surface_AOI.1,c(exX,exY))
res(source_surface_AOI)
saveRDS(source_surface_AOI, file = 'tmp/AOI/source_surface_AOI')
writeRaster(source_surface_AOI, filename=file.path(ConnDir,paste0('source_surface_AOI.tif')), overwrite=TRUE)


